[package]
name = "pixel-test-2"
version = "0.1.0"
authors = ["teevik <teemu.vikoren@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { version = "0.5", features = ["dynamic"] }
bevy-inspector-egui = "0.5"
rand = "0.8"
smallvec = "1.6"
shrinkwraprs = "0.3"
itertools = "0.10"