[package]
name = "pixel-test-2"
version = "0.1.0"
authors = ["teevik <teemu.vikoren@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
rand = "0.8"
smallvec = "1.6"
shrinkwraprs = "0.3"
itertools = "0.10"
arr_macro = "0.1"